ACCUMULATION_STEPS: 1
ACTIVATION: ReLU
AUX_LOSS: true
AUX_LOSS_WEIGHT:
- 1.0
- 1.0
- 1.0
- 1.0
- 1.0
AVAILABLE_GPUS: 0,1,2,3,4,5,6,7
BACKBONE: resnet50
BATCH_SIZE: 1
CHECKPOINT_LEVEL: 2
CLIP_MAX_NORM: 0.1
COCO_SIZE: true
CONFIG_PATH: ./configs/train_mot17.yaml
DATASET: MOT17
DATA_PATH: null
DATA_ROOT:
DET_SCORE_THRESH: 0.5
DEVICE: cuda
DROPOUT: 0.0
EPOCHS: 130
EVAL_DATA_SPLIT: val
EVAL_DIR: null
EVAL_MODE: specific
EVAL_MODEL: null
EVAL_PORT: null
EVAL_THREADS: 1
EXTRA_TRACK_ATTN: false
FFN_DIM: 2048
FP_INSERT_RATE: 0.0
GIT_VERSION: null
HIDDEN_DIM: 256
LONG_MEMORY_LAMBDA: 0.01
LOSS_WEIGHT_FOCAL: 2
LOSS_WEIGHT_GIOU: 2
LOSS_WEIGHT_L1: 5
LR: 0.0002
LR_BACKBONE: 2.0e-05
LR_DROP_MILESTONES:
- 120
LR_DROP_RATE: 0.1
LR_POINTS: 2.0e-05
LR_SCHEDULER: MultiStep
MATCH_COST_BBOX: 5
MATCH_COST_CLASS: 2
MATCH_COST_GIOU: 2
MERGE_DET_TRACK_LAYER: 1
MISS_TOLERANCE: 15
MODE: train
MOTION_LAMBDA: 0.5
MOTION_MAX_LENGTH: 5
MOTION_MIN_LENGTH: 3
MOTSYNTH_RATE: null
MULTI_CHECKPOINT: false
NUM_DEC_LAYERS: 6
NUM_DEC_POINTS: 4
NUM_DET_QUERIES: 300
NUM_ENC_LAYERS: 6
NUM_ENC_POINTS: 4
NUM_FEATURE_LEVELS: 4
NUM_HEADS: 8
NUM_WORKERS: 4
ONLY_TRAIN_QUERY_UPDATER_AFTER: 130
OUTPUTS_DIR: ./outputs/memotr_mot17/
OVERFLOW_BBOX: true
PRETRAINED_MODEL: D:\Thesis\DamnShit\Hello\MeMOTR_IKUN\dab_deformable_detr.pth

RESULT_SCORE_THRESH: 0.5
RESUME: null
RESUME_SCHEDULER: true
RETURN_INTER_DEC: true
REVERSE_CLIP: 0.0
SAMPLE_INTERVALS:
- 10
SAMPLE_LENGTHS:
- 2
- 3
- 4
- 5
SAMPLE_MODES:
- random_interval
SAMPLE_MOT17_JOIN: 0
SAMPLE_STEPS:
- 60
- 100
SEED: 42
SUBMIT_DATA_SPLIT: test
SUBMIT_DIR: null
SUBMIT_MODEL: null
TP_DROP_RATE: 0.0
TRACK_SCORE_THRESH: 0.5
UPDATE_THRESH: 0.5
USE_CHECKPOINT: true
USE_CROWDHUMAN: true    # we should set this to true if we want to use CrowdHuman dataset
USE_DAB: true
USE_DISTRIBUTED: true
USE_MOTION: false
USE_MOTSYNTH: null
VISUALIZE: false
WEIGHT_DECAY: 0.0001
# Aux Loss Weight
AUX_LOSS_WEIGHT: [1.0, 1.0, 1.0, 1.0, 1.0]
FREEZE_MEMOTR: False


FREEZE_MEMOTR: False

FEATURE_DIM: 1024
FFN_DIM: 2048
FP_INSERT_RATE: 0.0
FREEZE_MEMOTR: true
GET_DATA_SUBSET: false
GIT_VERSION: null
HIDDEN_DIM: 256
IKUN_THRESH: 0.5
IMG_HW:
- !!python/tuple
  - 224
  - 224
- !!python/tuple
  - 448
  - 448
- !!python/tuple
  - 672
  - 672
KUM_MODE: cascade attention

RANDOM_CROP_RATIO:
- 0.8
- 1.0

NORM_MEAN:
- 0.48145466
- 0.4578275
- 0.40821073
NORM_STD:
- 0.26862954
- 0.26130258
- 0.27577711

TRUNCATION: 10
TG_EPOCH: 0